In [1]:
import torch

a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [2]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)

tensor([[[0.9015, 0.6950, 0.9186],
         [0.2787, 0.8886, 0.2835],
         [0.4964, 0.4520, 0.3883]],

        [[0.3830, 0.3308, 0.9887],
         [0.3215, 0.1876, 0.6071],
         [0.1998, 0.9852, 0.2075]],

        [[0.1797, 0.9807, 0.7238],
         [0.9294, 0.0499, 0.8757],
         [0.2491, 0.9299, 0.1699]]])


In [3]:
from PIL import Image
import numpy as np

img = Image.open("cat.jpg")
c = torch.as_tensor(np.array(img))
print(c.shape)

torch.Size([1602, 1200, 3])


In [4]:
a = torch.arange(10)
b = torch.ones(10)
print(f"{a = }")
print(f"{b = }")
print(f"{a + b = }")

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [5]:
a = torch.rand(4)
b = torch.rand(5)
print(f"{a + b =}")

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [29]:
a = torch.rand(1_000_000_000, device="mps")
b = torch.rand(1_000_000_000, device="mps")
c = a + b

In [30]:
import gc

del a
del b

gc.collect()

0

In [32]:
a = torch.arange(6)
# a.shape
# a.view(2, 3) # doesn't copy underlying data
a.reshape(2, 3) # copies underlying data

tensor([[0, 1, 2],
        [3, 4, 5]])

In [33]:
a = torch.rand(2, 3)
print(a)
print(a.mT)

tensor([[0.8241, 0.1304, 0.5939],
        [0.4855, 0.8021, 0.2884]])
tensor([[0.8241, 0.4855],
        [0.1304, 0.8021],
        [0.5939, 0.2884]])


In [35]:
a = torch.rand(2, 3, 4)
print(a)
print(a.permute(1, 2, 0))

tensor([[[0.6004, 0.1818, 0.8273, 0.2527],
         [0.7550, 0.2499, 0.6964, 0.6842],
         [0.6905, 0.4702, 0.2954, 0.2687]],

        [[0.7994, 0.2788, 0.6374, 0.3235],
         [0.3576, 0.0173, 0.5572, 0.7696],
         [0.7770, 0.8057, 0.2735, 0.4764]]])
tensor([[[0.6004, 0.7994],
         [0.1818, 0.2788],
         [0.8273, 0.6374],
         [0.2527, 0.3235]],

        [[0.7550, 0.3576],
         [0.2499, 0.0173],
         [0.6964, 0.5572],
         [0.6842, 0.7696]],

        [[0.6905, 0.7770],
         [0.4702, 0.8057],
         [0.2954, 0.2735],
         [0.2687, 0.4764]]])


In [37]:
a = torch.arange(6)
b = a[None, :, None]
print(b.shape)
print(a)
print(b)


torch.Size([1, 6, 1])
tensor([0, 1, 2, 3, 4, 5])
tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5]]])


In [41]:
a = torch.arange(6).view(3, 2)
b = a[None, :, :, None]
print(b.shape)
print(a)
print(b)


torch.Size([1, 3, 2, 1])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[[[0],
          [1]],

         [[2],
          [3]],

         [[4],
          [5]]]])


In [45]:
a = torch.arange(6).view(3, 2, 1, 1)
# print(a[..., 0].shape)
print(a.squeeze(-1).shape)
# print(a.squeeze().shape) # NEVER DO THIS, i.e. call squeeze without specifying the dimension

torch.Size([3, 2, 1])


In [53]:
# broadcasting
a = torch.arange(4).view(4, 1)
b = torch.arange(5).view(1, 5)*10
print(f"{a = }")
print(f"{b = }")
print(f"{a + b = }")
print(f"{a * b = }")

a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])
a + b = tensor([[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41],
        [ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]])
a * b = tensor([[  0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40],
        [  0,  20,  40,  60,  80],
        [  0,  30,  60,  90, 120]])


In [54]:
a = torch.rand(2, 4)
b = torch.rand(4, 5)
a @ b

tensor([[1.2179, 0.9018, 0.6231, 1.3489, 1.1937],
        [0.9727, 0.7536, 0.5512, 1.3665, 1.3673]])

In [55]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
for i in range(10):
    for j in range(10):
        d[i, j] = (x[i] - x[j]).pow(2).sum()

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)

In [56]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx = 0, (-1, -1)
for i in range(10):
    for j in range(10):
        if (x[i] - x[j]).pow(2).sum() > max_dist:
            max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)

print(max_dist, max_idx)

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

tensor(20.9373) (5, 8)
tensor(20.9373) (tensor(5), tensor(8))


In [57]:
a = torch.rand(2, 4)
b = torch.rand(4)
c = b @ a.mT
print(c.shape)
print(torch.linalg.norm(b))
# print(b.pow(2).sum().sqrt())

torch.Size([2])
tensor(0.9717)
