In [1]:
import torch
import torch.distributions as dist


In [16]:
## Create a Bernoulli distribution
bernoulli = dist.Bernoulli(probs=torch.tensor([0.5]))
print(bernoulli)

## Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])


In [17]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.5109999775886536
Variance: 0.2501291334629059


In [19]:
### Create a Normal distribution
normal = dist.Normal(loc=torch.tensor([0.0]), scale=torch.tensor([1.0]))

## Sample from the distribution
for _ in range(10):
    print(normal.sample())

tensor([0.3758])
tensor([3.1852])
tensor([0.4641])
tensor([0.3552])
tensor([-2.0012])
tensor([0.1633])
tensor([-0.2847])
tensor([-0.1499])
tensor([0.6234])
tensor([0.0490])


In [25]:
# Sample from the distribution
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: -0.027174880728125572
Variance: 0.9410486817359924
