In [134]:
%load_ext autoreload
%autoreload 2

import torch
from deeplearning.homework_01 import PyTorchBasics

torch.manual_seed(42)

basics = PyTorchBasics()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
# create an example 1d tensor
x = torch.tensor([1, 2, 3, 4, 5])

basics.make_it_pytorch_1(x)

tensor([1, 4])

In [52]:
# create an example 3d tensor
x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

basics.make_it_pytorch_2(x)

tensor([[ 3,  6],
        [ 9, 12]])

In [53]:
# create an example 3d tensor with some duplicated values (random order)
x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]]])

basics.make_it_pytorch_3(x)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [258]:
# create an example 2d tensor of floats
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

# create an example 3d tensor of floats
y = torch.tensor([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]])

(y > x.mean()).sum()

tensor(7)

In [77]:
# create an example 2d tensor of floats
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

basics.make_it_pytorch_5(x)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [82]:
# create an example 2d tensor of floats
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

basics.make_it_pytorch_6(x)

tensor([1., 5.])

In [93]:
# create an example 2d tensor of floats
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

basics.make_it_pytorch_7(x)

AttributeError: 'PyTorchBasics' object has no attribute 'make_it_pytorch_'

In [92]:
# create an example 2d tensor of floats
x = torch.tensor([1.0, 2.0, 3.0])

basics.make_it_pytorch_8(x)

tensor([1., 3., 6.])

In [101]:
# create an example 2d tensor of floats
x = torch.tensor([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
print(x)

basics.make_it_pytorch_9(x)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


tensor([[ 1.,  2.,  3.],
        [ 3.,  6.,  9.],
        [ 6., 12., 18.]])

In [105]:
# create an example 2d tensor of random floats
x = torch.randn(3, 3)
print(x)

basics.make_it_pytorch_10(x, 0.5)

tensor([[-0.7433,  0.1315,  1.1802],
        [ 1.4522,  0.9996, -0.6195],
        [-1.8084, -0.6441,  0.7226]])


tensor([[0.0000, 0.0000, 1.1802],
        [1.4522, 0.9996, 0.0000],
        [0.0000, 0.0000, 0.7226]])

In [152]:
torch.manual_seed(42)

x = torch.randn(3, 3)
print(x)

basics.make_it_pytorch_11(x, 0.5)
# torch.where(x < 0.5)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


tensor([[0, 0, 0, 1, 1, 1, 2, 2],
        [0, 1, 2, 0, 1, 2, 1, 2]])

In [167]:
torch.manual_seed(42)
x = torch.randn(3, 3)
m = torch.randint(0, 2, (3, 3), dtype=torch.bool)

print(x)
print(m)

basics.make_it_pytorch_12(x, m)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
tensor([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])


tensor([ 0.3367,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,  0.4617])

In [198]:
x = torch.randn(3)
y = torch.randn(3)

print(x)
print(y)

basics.make_it_pytorch_extra_1(x, y)

tensor([0.3367, 0.1288, 0.2345])
tensor([ 0.2303, -1.1229, -0.1863])


tensor([-0.2079,  0.1057, -0.0041, -1.3532,  0.9365])

In [252]:
torch.manual_seed(42)
x = torch.randn(4)
y = x + torch.randint(0, 2, (4,), dtype=torch.float32)
print(x)
print(y)

basics.make_it_pytorch_extra_2(x, y)

tensor([0.3367, 0.1288, 0.2345, 0.2303])
tensor([0.3367, 1.1288, 0.2345, 0.2303])


tensor(3)