In [44]:
from pathlib import Path

import torch

from deeplearning.homework_03.homework.datasets.road_dataset import RoadDataset, load_data

In [30]:
data_path = Path().cwd().parent / "homework_03" / "drive_data"
train_data = load_data(data_path / "train", shuffle=True, batch_size=1, num_workers=2)


Loaded 8000 samples from 16 episodes


In [31]:
for batch in train_data:
    image = batch["image"]
    track = batch["track"]
    depth = batch["depth"]
    break

In [39]:
print(image.shape)
print(image)

torch.Size([1, 3, 96, 128])
tensor([[[[0.4392, 0.4431, 0.4431,  ..., 0.4039, 0.4196, 0.4392],
          [0.4275, 0.4314, 0.4353,  ..., 0.4196, 0.4275, 0.4353],
          [0.4157, 0.4196, 0.4275,  ..., 0.4314, 0.4314, 0.4275],
          ...,
          [0.6157, 0.6314, 0.6549,  ..., 0.6510, 0.6627, 0.6706],
          [0.6353, 0.6392, 0.6510,  ..., 0.6510, 0.6627, 0.6784],
          [0.6745, 0.6706, 0.6627,  ..., 0.6627, 0.6784, 0.6941]],

         [[0.4392, 0.4431, 0.4431,  ..., 0.4039, 0.4196, 0.4392],
          [0.4275, 0.4314, 0.4353,  ..., 0.4196, 0.4275, 0.4353],
          [0.4157, 0.4196, 0.4275,  ..., 0.4314, 0.4314, 0.4275],
          ...,
          [0.6157, 0.6314, 0.6549,  ..., 0.6510, 0.6627, 0.6706],
          [0.6353, 0.6392, 0.6510,  ..., 0.6510, 0.6627, 0.6784],
          [0.6745, 0.6706, 0.6627,  ..., 0.6627, 0.6784, 0.6941]],

         [[0.4392, 0.4431, 0.4431,  ..., 0.4039, 0.4196, 0.4392],
          [0.4275, 0.4314, 0.4353,  ..., 0.4196, 0.4275, 0.4353],
          [0.4

In [41]:
r1 = image[0, 0, :, :]
print(r1.shape)
print(r1)

torch.Size([96, 128])
tensor([[0.4392, 0.4431, 0.4431,  ..., 0.4039, 0.4196, 0.4392],
        [0.4275, 0.4314, 0.4353,  ..., 0.4196, 0.4275, 0.4353],
        [0.4157, 0.4196, 0.4275,  ..., 0.4314, 0.4314, 0.4275],
        ...,
        [0.6157, 0.6314, 0.6549,  ..., 0.6510, 0.6627, 0.6706],
        [0.6353, 0.6392, 0.6510,  ..., 0.6510, 0.6627, 0.6784],
        [0.6745, 0.6706, 0.6627,  ..., 0.6627, 0.6784, 0.6941]])


In [36]:
print(track.shape)
print(track)

torch.Size([1, 96, 128])
tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]])


In [42]:
t1 = track[0, :, :]
print(t1.shape)
print(t1)

torch.Size([96, 128])
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])


In [48]:
t1 = track[0, :, :]
nonzero_indices = torch.nonzero(t1)
print(nonzero_indices)


tensor([[ 43,  88],
        [ 43,  89],
        [ 44,  34],
        [ 44,  35],
        [ 44,  36],
        [ 44,  87],
        [ 44,  88],
        [ 44,  89],
        [ 44,  90],
        [ 44,  91],
        [ 45,  31],
        [ 45,  32],
        [ 45,  33],
        [ 45,  34],
        [ 45,  35],
        [ 45,  36],
        [ 45,  37],
        [ 45,  86],
        [ 45,  87],
        [ 45,  88],
        [ 45,  89],
        [ 45,  90],
        [ 45,  91],
        [ 45,  92],
        [ 46,  29],
        [ 46,  30],
        [ 46,  31],
        [ 46,  32],
        [ 46,  33],
        [ 46,  34],
        [ 46,  35],
        [ 46,  36],
        [ 46,  37],
        [ 46,  38],
        [ 46,  87],
        [ 46,  88],
        [ 46,  89],
        [ 46,  90],
        [ 46,  91],
        [ 46,  92],
        [ 46,  93],
        [ 46,  94],
        [ 47,  27],
        [ 47,  28],
        [ 47,  29],
        [ 47,  30],
        [ 47,  31],
        [ 47,  32],
        [ 47,  33],
        [ 47,  34],


In [38]:
print(depth.shape)
print(depth)

torch.Size([1, 96, 128])
tensor([[[0.9292, 0.9304, 0.9315,  ..., 0.9245, 0.9233, 0.9221],
         [0.9292, 0.9304, 0.9315,  ..., 0.9245, 0.9233, 0.9221],
         [0.9292, 0.9304, 0.9315,  ..., 0.9245, 0.9233, 0.9221],
         ...,
         [0.6187, 0.6187, 0.6187,  ..., 0.6199, 0.6199, 0.6199],
         [0.6121, 0.6122, 0.6122,  ..., 0.6133, 0.6133, 0.6134],
         [0.6056, 0.6056, 0.6056,  ..., 0.6068, 0.6068, 0.6068]]])


In [27]:
import numpy as np

# Load the info.npz file
info_path = data_path / "train" / "cornfield_crossing_00" / "info.npz"
info = np.load(info_path, allow_pickle=True)

# Print the keys in the file
print("Keys in info.npz:", info.files)

# Access the track information
track = info['track'].item()
print("\nTrack information:", track)

Keys in info.npz: ['track', 'frames']

Track information: {'path_nodes': array([[[ 0.40949988,  0.355     , 18.822     ],
        [ 0.40949988,  0.355     , 24.698     ]],

       [[ 0.40949988,  0.355     , 24.698     ],
        [ 0.40949988,  0.355     , 30.573     ]],

       [[ 0.40949988,  0.355     , 30.573     ],
        [ 0.40949988,  0.355     , 61.649     ]],

       ...,

       [[ 0.40949988,  0.355     ,  7.071     ],
        [ 0.40949988,  0.355     , 12.947     ]],

       [[ 0.40949988,  0.355     , 12.947     ],
        [ 0.40949988,  0.355     , 18.17      ]],

       [[ 0.40949988,  0.355     , 18.17      ],
        [ 0.40949988,  0.355     , 18.822     ]]],
      shape=(273, 2, 3), dtype=float32), 'path_distance': array([[   0.       ,    5.8759995],
       [   5.8759995,   11.750999 ],
       [  11.750999 ,   42.826996 ],
       [  42.826996 ,   52.634705 ],
       [  52.634705 ,   57.86182  ],
       [  57.86182  ,   60.793526 ],
       [  60.793526 ,   63.63824  

In [54]:
pixels = 100
background = 90
road = 10

true_pos_background = 70
false_pos_background = 20
false_neg_background = 20

iou_background = true_pos_background / (true_pos_background + false_pos_background + false_neg_background)
print(iou_background)

0.6363636363636364


In [57]:
pixels = 100
background = 90
road = 10

true_pos_background = 90
false_pos_background = 10
false_neg_background = 0

true_pos_road = 0
false_pos_road = 0
false_neg_road = 10

iou_road = true_pos_road / (true_pos_road + false_pos_road + false_neg_road)
print(f"Road IoU: {iou_road}")

iou_background = true_pos_background / (true_pos_background + false_pos_background + false_neg_background)
print(f"Background IoU: {iou_background}")

Road IoU: 0.0
Background IoU: 0.9


## Load model

In [1]:
from pathlib import Path

import torch

In [2]:
hw_path = Path().cwd().parent / "homework_03" / "homework"
logs_path = hw_path / "logs"
print(logs_path)

/Users/timreddick/code/AI394D-deep-learning/deeplearning/homework_03/homework/logs


In [28]:
# Access the frames information
frames = info['frames'].item()
print("\nFrame keys:", frames.keys())


Frame keys: dict_keys(['V', 'P', 'location', 'front', 'velocity', 'distance_down_track'])


In [ ]:
frames