In [5]:
from pathlib import Path

from deeplearning.homework_04.grader.datasets import road_dataset

path = Path().cwd().parent / "homework_04" / "drive_data" / "val"
print(path)


/Users/timreddick/code/AI394D-deep-learning/deeplearning/homework_04/drive_data/val


In [6]:
data = road_dataset.load_data(path)

Loaded 2000 samples from 4 episodes


In [9]:
import torch

# Create a 1D tensor with 12 elements
original_tensor = torch.arange(12)
print("Original Tensor:")
print(original_tensor)

# Reshape the tensor into a 2D tensor of shape (3, 4)
reshaped_tensor = original_tensor.reshape(3, 4)
print("\nReshaped Tensor (3x4):")
print(reshaped_tensor)

# Reshape the tensor into a 3D tensor of shape (2, 2, 3)
reshaped_tensor_3d = original_tensor.reshape(2, 2, 3)
print("\nReshaped Tensor (2x2x3):")
print(reshaped_tensor_3d)

# Demonstrating that the original tensor remains unchanged
print("\nOriginal Tensor After Reshaping:")
print(original_tensor)

# What does -1 mean in reshape?
# The -1 in reshape allows PyTorch to automatically calculate the size of that dimension based on the other dimensions and the total number of elements.
# For example, if we want to reshape the original tensor into a shape of (3, -1), PyTorch will automatically determine the second dimension size.
reshaped_tensor_auto = original_tensor.reshape(3, -1)
print("\nReshaped Tensor with -1 (3x-1):")
print(reshaped_tensor_auto)


Original Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped Tensor (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped Tensor (2x2x3):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

Original Tensor After Reshaping:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped Tensor with -1 (3x-1):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
